spring:
  mvc:
    pathmatch:
      #Swagger3需要的配置
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: dm.jdbc.driver.DmDriver
  #            url: jdbc:dm://47.99.124.228:30236?schema=PERSON&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          url: jdbc:dm://47.99.124.228:11036?schema=CHILD_REARING_PLATFORM_DEV&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: SYSDBA
          password: SYSDBA001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

recovery:
  signing-secret: 123456

#storage:
#  mode: local
#  local:
#    endpoint: http://www.baidu.com
#    root: /Users/tiger/Documents/klarity/storage/

logging:
  config: classpath:logback.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

file:
  domain: http://${host.ip}:${host.port}/data/syzh/backend/static/image/
#
#action:
#  attribute: /data/syzh/backend/json/action.json
#scale-table:
#  file: /data/syzh/backend/json/scaleTable.json
#  result:
#    cerebralPalsyPath: /data/syzh/backend/json/result.json
#  video-mark-param: /data/syzh/backend/json/videoMarkParam.json
#  actionVideoFilePath: /data/syzh/backend/json/video.json
#  abnormalMethodFilePath: /data/syzh/backend/json/abnormalIterm.json
#  trainMethodFilePath: /data/syzh/backend/json/train.json
action:
  attribute: /Users/Zhuanz/fushujiankang2.0/json/action.json

scale-table:
  file: /Users/Zhuanz/fushujiankang2.0/json/scaleTable.json
  result:
    cerebralPalsyPath: /Users/Zhuanz/fushujiankang2.0/json/result.json
  video-mark-param: /Users/Zhuanz/fushujiankang2.0/json/videoMarkParam.json
  actionVideoFilePath: /Users/Zhuanz/fushujiankang2.0/json/video.json
  abnormalMethodFilePath: /Users/Zhuanz/fushujiankang2.0/json/abnormalIterm.json
  trainMethodFilePath: /Users/Zhuanz/fushujiankang2.0/json/train.json

storage:
  mode: cloud
  temp-storage-root: /data/syzh/backend/static
  outside:
    endpoint: http://${host.ip}:${host.port}
#  local:
#    endpoint: http://platform-test.fushuhealth.com/recovery/storage
#    root: /data/app/fushu/backend/platform/storage/
#    file-url-base: /platform/storage
  cloud:
    access-key: 5tWU4jx332LnEkvTlzONEFO00KdRXQApLvLQGmIc
    secret-key: oO08CqPkhJdX7l_gV8KyFm_qpNncC9UnQptmXl6Z
    endpoint: hz-storage.fushuhealth.com
    bucket: fushu-hangzhou

video:
  pm3u8: pm3u8/0/expires/43200
  wm-url: kodo://fushu-recovery/logo.jpg
  qiniu-pipeline: recovery-video

host:
  ip: 47.99.124.228
  port: 11080