package com.fushuhealth.recovery.dal.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * @TableName organization
 */
@Data
public class Organization implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private Long id;

    /**
     * 机构名字
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private String orgCode;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private Byte status;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private Long created;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private Long updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated Wed Jan 06 15:45:30 CST 2021
     */
    private static final long serialVersionUID = 1L;
}