package com.fushuhealth.recovery.dal.entity;

import lombok.Builder;
import lombok.Data;

import java.io.Serializable;

/**
 * @TableName role
 */
@Data
@Builder
public class Role implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Long id;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Long organizationId;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private String roleName;

    /**
     * 系统角色1，机构角色 2
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Byte roleType;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Byte status;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Long created;

    /**
     * 
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private Long updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Jan 06 15:40:18 CST 2021
     */
    private static final long serialVersionUID = 1L;
}