spring:
  datasource:
    url: jdbc:mysql://192.168.1.112:3306/child_rearing_platform_dev?useUnicode=true&characterEncoding=utf8
    username: root
    password: wf817628
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

recovery:
  signing-secret: 123456

storage:
  mode: local
  local:
    endpoint: http://www.baidu.com
    root: /Users/tiger/Documents/klarity/storage/

logging:
  config: classpath:logback.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30